apiVersion: apps/v1
kind: Deployment
metadata:
  name: hero-manager-frontend
  labels:
    name: hero-manager-frontend
spec:
  selector:
    matchLabels:
      name: hero-manager-frontend
  replicas: 1
  template:
    metadata:
      labels:
        name: hero-manager-frontend
    spec:
      containers:
        - name: hero-manager-frontend
          image: docker.io/library/hero_manager_frontend_image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources: {}
          env:
            - name: DB_HOST
              value: hero-manager-database
            - name: DB_PORT
              value: "27017"
            - name: DB_NAME
              value: heroManager
            - name: PORT
              value: "8081"
