apiVersion: apps/v1
kind: Deployment
metadata:
  name: hero-manager-database
  labels:
    name: hero-manager-database
spec:
  selector:
    matchLabels:
      name: hero-manager-database
  replicas: 1
  template:
    metadata:
      labels:
        name: hero-manager-database
    spec:
      containers:
        - name: hero-manager-database
          image: docker.io/library/mongo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          resources: {}
          env:
            - name: PORT
              value: "27017"

